build:
  symlink-install: true
  base-paths: ["@(ros_ws_root)/src"]
  build-base: "@(ros_ws_root)/build"
  install-base: "@(ros_ws_root)/install"
  cmake-args:
    - -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

test:
  build-base: "@(ros_ws_root)/build"
  install-base: "@(ros_ws_root)/install"
  log-base: "@(ros_ws_root)/log"
  event-handlers:
    - console_direct+

test-result:
  'yes': true
  test-result-base: "@(ros_ws_root)/build"

clean.workspace:
  'yes': true
  base-select:
    - build
    - install
    - log
    - test_result
  build-base: "@(ros_ws_root)/build"
  install-base: "@(ros_ws_root)/install"
  log-base: "@(ros_ws_root)/log"
  test-result-base: "@(ros_ws_root)/build"

'':
  log-base: "@(ros_ws_root)/log"
